DELETE FROM USER_VOTE;
DELETE FROM "USER";
DELETE FROM POST_TAG;
DELETE FROM TAG;
DELETE FROM POST_DETAILS;
DELETE FROM POST_COMMENT_DETAILS;
DELETE FROM POST_COMMENT;
DELETE FROM POST;

ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART START WITH 1;