package com.vladmihalcea.hpjp.hibernate.identifier.override.identity2sequence;

import com.vladmihalcea.hpjp.util.AbstractTest;
import com.vladmihalcea.hpjp.util.providers.Database;
import org.hibernate.boot.model.naming.Identifier;
import org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl;
import org.hibernate.cfg.*;
import org.hibernate.engine.jdbc.env.spi.JdbcEnvironment;
import org.hibernate.tool.schema.Action;
import org.junit.jupiter.api.Test;

import java.util.Locale;
import java.util.Properties;

public class PostgreSQLIdentityToSequenceTest extends AbstractTest {

    @Override
    protected Class<?>[] entities() {
        return new Class<?>[] {
            Post.class,
            PostComment.class
        };
    }

    @Override
    protected Database database() {
        return Database.POSTGRESQL;
    }

    @Override
    protected void additionalProperties(Properties properties) {
        properties.put(SchemaToolingSettings.HBM2DDL_AUTO, Action.NONE);
        properties.put(BatchSettings.STATEMENT_BATCH_SIZE, "5");
        properties.put(BatchSettings.ORDER_INSERTS, Boolean.TRUE);
        properties.put(BatchSettings.ORDER_UPDATES, Boolean.TRUE);
        properties.put(
            MappingSettings.PHYSICAL_NAMING_STRATEGY,
            SequenceNameNamingStrategy.class
        );
    }

    @Override
    protected void beforeInit() {
        executeStatement("drop table if exists post cascade");
        executeStatement("drop table if exists post_comment cascade");
        executeStatement("create table post (id bigint generated by default as identity, title varchar(255), primary key (id))");
        executeStatement("create table post_comment (id bigint generated by default as identity, post_id bigint, review varchar(255), primary key (id))");
        executeStatement("alter table if exists post_comment add constraint FK_post_comment_post foreign key (post_id) references post");
    }

    @Test
    public void test() {
        doInJPA(entityManager -> {
            for (int i = 1; i <= 5; i++) {
                Post post = new Post();
                post.setTitle(String.format("Post nr %d", i + 1));
                entityManager.persist(post);

                PostComment postComment = new PostComment();
                postComment.setReview(String.format("Post nr %d", i + 1));
                postComment.setPost(post);
                entityManager.persist(postComment);
            }
        });
    }

    public static class SequenceNameNamingStrategy extends PhysicalNamingStrategyStandardImpl {
        @Override
        public Identifier toPhysicalSequenceName(Identifier logicalName, JdbcEnvironment context) {
            String tableName = logicalName.getCanonicalName().toLowerCase(Locale.ROOT).replace("_seq", "");
            return Identifier.toIdentifier(tableName + "_id_seq", logicalName.isQuoted());
        }
    }
}
